# Generated by Django 3.2.5 on 2021-07-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('notes', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Staffs Group',
                'ordering': ['name'],
            },
            bases=('auth.group',),
        ),
    ]
